---
version: '3'
services:
    build_war:
        build:
            context: ./docker
            dockerfile: maven.Dockerfile
        volumes:
            - app:/tmp

    dep_war:build: 
        image: tomcat:9-jdk11
        ports:
            - '8080:8080'
        volumes:
            app:/usr/local/tomcat/webapps

volumes:
    app: